@HostAddress = http://localhost:5094
@accessToken = eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjAxOWNmMWIzLWVjOGQtN2FhMS1hYzczLTcyMzRiODU1ZDJjMSIsImVtYWlsIjoiZi1jYWtpcm9nbHVAb3V0bG9vay5jb20iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiZmNha2lyb2dsdTY0NjYiLCJqdGkiOiIzY2JhNjQ4Mi1kYmZhLTRiMDQtOGQyMi03NTEzYmNmYTc5ZTMiLCJuYmYiOjE3NzM1ODE2MjksImV4cCI6MTc3MzU5NjAyOSwiaXNzIjoiYXBpLmNpbmVtYS10aWNrZXRpbmctc3l0ZW0uY29tIn0._NIE5DiB1iABG7SKUnNS1ecFwdPUGHoBH-XIh2o6lDo

###
POST {{HostAddress}}/api/v1/ticketing/seatholds
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "seatPositions": [
    {
      "row": "A",
      "number": 1
    },
    {
      "row": "B",
      "number": 1
    }
  ],
  "ScreeningDate": "2025-10-10",
  "scheduledMovieShowId": "019cf1b3-d207-739d-b137-02345083110f"
}

###
POST {{HostAddress}}/api/v1/ticketing/seatholds/confirm
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "ScreeningDate": "2025-10-10",
  "scheduledMovieShowId": "019cf1b3-d207-739d-b137-02345083110f"
}

###
POST {{HostAddress}}/api/v1/ticketing/issuance
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "ScreeningDate": "2025-10-10",
  "scheduledMovieShowId": "019cf1b3-d207-739d-b137-02345083110f"
}
###
POST {{HostAddress}}/api/v1/ticketing/reservation
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "ScreeningDate": "2025-10-10",
  "scheduledMovieShowId": "0198d099-23eb-7568-9b05-19353f6a54e5"
}
###
POST {{HostAddress}}/api/v1/ticketing/reservation/confirm/0199b0f1-6372-7a3e-9b8a-f1949330fe50
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{accessToken}}
