@HostAddress = http://localhost:5094
@accessToken = eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjAxOThkMGFmLWNiODktNzQ5Ni04NTY3LWNjNTVhNWU5MDBkZiIsImVtYWlsIjoiZi1jYWtpcm9nbHVAb3V0bG9vay5jb20iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiZmNha2lyb2dsdTYxODAiLCJqdGkiOiI3ZTIxODU3Ny0yMGM1LTRjNDgtYWE5Yi0xMzQ2ZDNmMDI2ZDIiLCJuYmYiOjE3NTk2MTExMDMsImV4cCI6MTc1OTYyNTUwMywiaXNzIjoiYXBpLmNpbmVtYS10aWNrZXRpbmctc3l0ZW0uY29tIn0.lWAaxG49X222bJ9t9GdjZi3ssacjW2LdSEDuBY4rCcU
###
POST {{HostAddress}}/api/v1/catalogs/movies
Accept: application/json
Content-Type: application/json

{
  "title": "Inception 3",
  "originalTitle": "Inception",
  "description": "A mind-bending thriller that delves into the world of dreams.",
  "EarliestShowingDate": "2026-07-16T00:00:00Z",
  "duration": "01:30:00",
  "posterImageUrl":"http://wwww.abc.com",
  "supportedTechnology":1
}
###
GET {{HostAddress}}/api/v1/catalogs/movies
Accept: application/json

###
POST {{HostAddress}}/api/v1/catalogs/cinemas
Accept: application/json
Content-Type: application/json

{
  "name": "Galaxy Cinema Mall",
  "address": {
    "country": "Turkey",
    "city": "Istanbul",
    "district": "Beyoğlu",
    "street": "İstiklal Caddesi No: 123",
    "postalCode": "34430",
    "description": "Located in the heart of Beyoğlu, next to Galatasaray High School"
  }
}

###
GET {{HostAddress}}/api/v1/catalogs/cinemas
Accept: application/json
Accept-Language: tr

###


POST {{HostAddress}}/api/v1/catalogs/cinemas/0198d08e-2bd3-70a8-b586-0c5ca6a9bf77/hall
Accept: application/json
Content-Type: application/json
Accept-Language: en

{
  "cinemaId": "f93795b0-e16f-4d00-9fbf-7657e9257945",
  "name": "Hall 5 - Strandart Premium 2",
  "technologies": [1, 2],
  "seatList": [
    {
      "row": "A",
      "number": 1,
      "seatType": 0
    },
    {
      "row": "A",
      "number": 2,
      "seatType": 0
    },
    {
      "row": "A",
      "number": 3,
      "seatType": 1
    },
    {
      "row": "A",
      "number": 4,
      "seatType": 1
    },
    {
      "row": "B",
      "number": 1,
      "seatType": 0
    },
    {
      "row": "B",
      "number": 2,
      "seatType": 0
    },
    {
      "row": "B",
      "number": 3,
      "seatType": 2
    }
  ]
}
###
GET {{HostAddress}}/api/v1/catalogs/cinemas/0198d08e-2bd3-70a8-b586-0c5ca6a9bf77/hall
Accept: application/json

###
GET {{HostAddress}}/api/v1/schedules/halls/0198d08e-2bd3-70a8-b586-0c5ca6a9bf77/movies
Accept: application/json

###

POST {{HostAddress}}/api/v1/schedules/halls/0198d098-040c-7281-911a-adf62d676ffe/movies
Accept: application/json
Content-Type: application/json
{
  "movieId": "0198d096-d4c0-72b1-8f59-035c7e603523",
  "startTime": "19:00:00",
  "Price": {
    "Amount": 100,
    "Currency": "TRY"
  }
}
###
GET {{HostAddress}}/api/v1/schedules/halls/0198d098-040c-7281-911a-adf62d676ffe/movies
Accept: application/json
###
POST {{HostAddress}}/api/v1/accounts/auth/signup
Accept: application/json
Content-Type: application/json

{
  "email": "f-cakiroglu@outlook.com",
  "password": "Password12*",
  "firstName": "Fatih",
  "lastName": "Çakıroğlu"
}
###
POST {{HostAddress}}/api/v1/accounts/auth/signin
Accept: application/json
Content-Type: application/json

{
  "email": "f-cakiroglu@outlook.com",
  "password": "Password12*"
}
###
POST {{HostAddress}}/api/v1/ticketing/seatholds
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "seatPositions": [
    {
      "row": "A",
      "number": 1
    },
      {
      "row": "B",
      "number": 1
    }
  ],
  "ScreeningDate": "2025-10-10",
  "scheduledMovieShowId": "0198d099-23eb-7568-9b05-19353f6a54e5"
}
###
POST {{HostAddress}}/api/v1/ticketing/seatholds/confirm
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "ScreeningDate": "2025-10-10",
  "scheduledMovieShowId": "0198d099-23eb-7568-9b05-19353f6a54e5"
}
###
POST {{HostAddress}}/api/v1/ticketing/issuance
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "ScreeningDate": "2025-10-10",
  "scheduledMovieShowId": "0198d099-23eb-7568-9b05-19353f6a54e5"
}
###
POST {{HostAddress}}/api/v1/ticketing/reservation
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "ScreeningDate": "2025-10-10",
  "scheduledMovieShowId": "0198d099-23eb-7568-9b05-19353f6a54e5"
}
###
POST {{HostAddress}}/api/v1/ticketing/reservation/confirm/0199b0f1-6372-7a3e-9b8a-f1949330fe50
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{accessToken}}
###
POST {{HostAddress}}/api/v1/purchases
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "cardNumber": "4111111111111111",
  "cardHolderName": "FATIH CAKIROGLU",
  "cardExpirationDate": "12/2027",
  "cardSecurityNumber": "123",
  "price": {
    "amount": 100.00,
    "currency": "TRY"
  },
  "ticketIssuanceId": "0199021f-cf5f-7453-a0da-54b505c3defb"

}



