@HostAddress = http://localhost:5094

###
POST {{HostAddress}}/api/v1/catalogs/movies
Accept: application/json
Content-Type: application/json
{
  "title": "Inception 6",
  "originalTitle": "Inception",
  "description": "A mind-bending thriller that delves into the world of dreams.",
  "EarliestShowingDate": "2026-07-16T00:00:00Z",
  "duration": "01:30:00",
  "posterImageUrl":"http://wwww.abc.com",
  "supportedTechnology":1
}

###
GET {{HostAddress}}/api/v1/catalogs/movies
Accept: application/json

###
POST {{HostAddress}}/api/v1/catalogs/cinemas
Accept: application/json
Content-Type: application/json
{
  "name": "Galaxy Cinema Mall",
  "address": {
    "country": "Turkey",
    "city": "Istanbul",
    "district": "Beyoğlu",
    "street": "İstiklal Caddesi No: 123",
    "postalCode": "34430",
    "description": "Located in the heart of Beyoğlu, next to Galatasaray High School"
  }
}

###
GET {{HostAddress}}/api/v1/catalogs/cinemas
Accept: application/json
Accept-Language: tr

###


POST {{HostAddress}}/api/v1/catalogs/cinemas/01987042-86bf-762d-a34a-a0dc299d77fc/hall
Accept: application/json
Content-Type: application/json
Accept-Language: en
{
  "cinemaId": "f93795b0-e16f-4d00-9fbf-7657e9257945",
  "name": "Hall 5 - Strandart Premium",
  "technologies": [1, 2],
  "seatList": [
    {
      "row": "A",
      "number": 1,
      "seatType": 0
    },
    {
      "row": "A",
      "number": 2,
      "seatType": 0
    },
    {
      "row": "A",
      "number": 3,
      "seatType": 1
    },
    {
      "row": "A",
      "number": 4,
      "seatType": 1
    },
    {
      "row": "B",
      "number": 1,
      "seatType": 0
    },
    {
      "row": "B",
      "number": 2,
      "seatType": 0
    },
    {
      "row": "B",
      "number": 3,
      "seatType": 2
    }
  ]
}

###
GET {{HostAddress}}/api/v1/catalogs/cinemas/01987042-86bf-762d-a34a-a0dc299d77fc/hall
Accept: application/json

###
GET {{HostAddress}}/api/v1/schedules/halls/01987042-86bf-762d-a34a-a0dc299d77fc/movies
Accept: application/json

###

POST {{HostAddress}}/api/v1/schedules/halls/01987058-3e88-7c83-814e-ec3033ef4fb7/movies
Accept: application/json
Content-Type: application/json
{
  "movieId": "01987057-d3d6-7a12-8075-cc1bbf9e4b76",
  "startTime": "22:05:00",
  "Price": {
    "Amount": 100,
    "Currency": "TRY"
  }
}
###
GET {{HostAddress}}/api/v1/schedules/halls/01987058-3e88-7c83-814e-ec3033ef4fb7/movies
Accept: application/json
###
POST {{HostAddress}}/api/v1/accounts/auth/signup
Accept: application/json
Content-Type: application/json
{
  "email": "f-cakiroglu@outlook.com",
  "password": "Password12*",
  "firstName": "Fatih",
  "lastName": "Çakıroğlu"
}
###
POST {{HostAddress}}/api/v1/accounts/auth/signin
Accept: application/json
Content-Type: application/json
{
  "email": "f-cakiroglu@outlook.com",
  "password": "Password12*"
}
